import fs from 'node:fs/promises';
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const DIR = 'assets/fonts';
const families = [
  /* Ethara brand faces: Roboto for display, DM Sans for body. */
  { key: 'roboto', q: 'Roboto:wght@100..900' },
  { key: 'dmsans', q: 'DM+Sans:opsz,wght@9..40,100..1000' },
  /* Neutral fallback system for non-brand work. */
  { key: 'inter', q: 'Inter:wght@100..900' },
  { key: 'sourceserif4', q: 'Source+Serif+4:opsz,wght@8..60,200..900' },
];
// keep only the subsets we actually need for business decks
const KEEP = ['latin', 'latin-ext'];
let out = '/* Local variable fonts. Generated by scripts/fetch-fonts.mjs - do not hand-edit. */\n';
for (const { key, q } of families) {
  const css = await (await fetch(`https://fonts.googleapis.com/css2?family=${q}&display=block`, { headers: { 'User-Agent': UA } })).text();
  // Google emits a /* subset */ comment before each @font-face block
  const blocks = css.split('/*').slice(1);
  let i = 0;
  for (const raw of blocks) {
    const subset = raw.slice(0, raw.indexOf('*/')).trim();
    if (!KEEP.includes(subset)) continue;
    const block = raw.slice(raw.indexOf('*/') + 2);
    const url = block.match(/https:\/\/[^)]*\.woff2/)?.[0];
    if (!url) continue;
    const file = `${key}-${subset}.woff2`;
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    await fs.writeFile(`${DIR}/${file}`, buf);
    console.log(`  ${file}  ${(buf.length / 1024).toFixed(0)} KB`);
    out += block.replace(/url\([^)]*\)/, `url("../fonts/${file}")`).trim() + '\n\n';
    i++;
  }
  if (!i) throw new Error(`no subsets captured for ${key}`);
}
await fs.writeFile('assets/css/fonts.css', out);
console.log('wrote assets/css/fonts.css');
